name: Stereogram Solver E2E Tests

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser to run e2e tests"
        required: true
        default: chrome
        type: choice
        options:
          - chrome
          - firefox

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      CYPRESS_BROWSER: ${{ github.event.inputs.browser || 'chrome' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --browser ${{ env.CYPRESS_BROWSER }} --env TAGS='not @ignore'

      - name: Upload JUnit Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: junit-results
          path: results/junit/

      - name: Report test results
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }} 
        with:
          name: JEST Tests
          path: results/junit/*.xml
          reporter: jest-junit
          fail-on-error: false

      - name: Merge mochawesome JSON reports
        if: ${{ !cancelled() }} 
        run: |
          mkdir -p cypress/reports/html
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/output.json

      - name: Generate mochawesome HTML report
        if: ${{ !cancelled() }} 
        run: |
          npx marge cypress/reports/output.json --reportDir cypress/reports/html --inline

      - name: Upload mochawesome HTML report
        if: ${{ !cancelled() }} 
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-report
          path: cypress/reports/html/output.html